name: test.yml

on:
  push:
    branches:
      - '**/*'
  pull_request:
    branches:
      - '**/*'

jobs:
  metadata:
    name: Reads workflow metadata
    if: false
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Reads workflow metadata
        id: metadata
        run: |
          file='${{ github.workspace }}/.github/workflows-metadata.yml'
          root='.workflows["${{ github.workflow }}"]'
          meta=$(yq $root $file)
          echo $meta
          echo "runs-on=$(yq "$root.runs-on | join(\",\")" $file)" >> $GITHUB_OUTPUT
          echo "job-monitor-labels=$(yq "$root.job-monitor-labels | join(\",\")" $file)" >> $GITHUB_OUTPUT
          echo "force-run-labels=$(yq "$root.force-run-labels | join(\",\")" $file)" >> $GITHUB_OUTPUT
          echo "run-group=true" >> $GITHUB_OUTPUT
          echo "run-label=true" >> $GITHUB_OUTPUT

      - name: Print metadata
        run: |
          echo "Workflow metadata:"
          echo "Runs on: ${{ steps.metadata.outputs.runs-on }}"
          echo "Job monitor labels: ${{ steps.metadata.outputs.job-monitor-labels }}"
          echo "Force run labels: ${{ steps.metadata.outputs.force-run-labels }}"

      - name: Run conditionally
        if: |
          steps.metadata.outputs.run-group == 'true' ||
          steps.metadata.outputs.run-label == 'true'
        run: echo "Tests executed"

  action-gate:
    name: Action Gate
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Gate All
        id: gate-all
        uses: ./.github/actions/gate
        with:
          target: |
            main
            feature
            task
          force-labels: |
            run-TestsA
            run-TestsB
            
      - name: Gate Feature
        id: gate-feature
        uses: ./.github/actions/gate
        with:
          target: |
            main
            feature
          force-labels: |
            run-TestsA
            run-TestsB

      - name: Gate Main
        id: gate-main
        uses: ./.github/actions/gate
        with:
          target: main
          force-labels: |
            run-TestsA
            run-TestsB
            
      - name: Run Tests A on task
        if: steps.gate-all.outputs.should-run
        run: echo "Running Tests A on task"
        
      - name: Run Tests B on task
        if: steps.gate-all.outputs.should-run
        run: echo "Running Tests A on task"

      - name: Run Tests A on feature
        if: steps.gate-feature.outputs.should-run
        run: echo "Running Tests A on feature"

      - name: Run Tests B on feature
        if: steps.gate-feature.outputs.should-run
        run: echo "Running Tests B on feature"

      - name: Run Tests A on main
        if: steps.gate-main.outputs.should-run
        run: echo "Running Tests A on main"

      - name: Run Tests B on main
        if: steps.gate-main.outputs.should-run
        run: echo "Running Tests B on main"
